## Steps
1. Reproducing kaggle https://www.kaggle.com/code/jamesloy/deep-learning-based-recommender-systems
2. Recreate all models in neural collaborative filtering

In [1]:
import os

os.chdir("/Users/yenchenchou/Documents/GitHub/recsys-benchmarks")

In [2]:
import random
import polars as pl
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets

In [3]:
a = torch.tensor([0,1])
b = torch.tensor([[1,0], [1,0]])

In [4]:
a + b

tensor([[1, 1],
        [1, 1]])

In [34]:
rnn = nn.RNN(4, 6, 2)
input = torch.randn(5, 3, 4)
h0 = torch.randn(2, 3, 6)
output, hn = rnn(input, h0)

In [37]:
output.shape

torch.Size([5, 3, 6])

In [40]:
hn

tensor([[[-0.0190, -0.0970, -0.3689,  0.4663, -0.3287,  0.0695],
         [ 0.3703,  0.1498, -0.1245,  0.1470, -0.1001,  0.6173],
         [-0.0416,  0.1351,  0.6027,  0.2984,  0.1480,  0.0488]],

        [[ 0.6485, -0.0534, -0.2013,  0.0575,  0.3006,  0.2300],
         [ 0.3248,  0.0816, -0.0351, -0.0488,  0.4219,  0.3162],
         [ 0.4656,  0.0340, -0.3150,  0.3634,  0.4965,  0.2523]]],
       grad_fn=<StackBackward0>)

In [35]:
for name, p in rnn.named_parameters():
    print(name, p)

weight_ih_l0 Parameter containing:
tensor([[ 0.1921, -0.1023, -0.1472, -0.1098],
        [-0.0159, -0.3776, -0.2007, -0.0532],
        [ 0.3471,  0.3105, -0.3979,  0.1555],
        [-0.2655, -0.2632,  0.1633,  0.3992],
        [ 0.0216,  0.0587, -0.1684, -0.3373],
        [-0.1523, -0.3571,  0.2357, -0.0322]], requires_grad=True)
weight_hh_l0 Parameter containing:
tensor([[-3.7485e-01, -3.9554e-01,  1.4590e-01, -5.8184e-02,  2.1411e-01,
          2.0833e-01],
        [-3.1138e-01, -3.6741e-01,  2.5246e-01, -1.5210e-01,  3.6096e-04,
          3.4081e-01],
        [ 3.4347e-01,  2.2671e-01, -1.1795e-01,  4.0751e-01,  3.2784e-01,
          5.6462e-02],
        [-2.7326e-01,  2.1881e-01,  4.0671e-01, -7.2140e-02, -1.7530e-01,
         -5.9384e-02],
        [-1.5332e-01,  3.8037e-01, -3.4873e-01, -3.4284e-01, -3.1794e-03,
         -2.1007e-01],
        [-3.6784e-02,  2.2802e-01,  3.6104e-01,  1.3276e-02,  7.8464e-02,
         -1.4848e-01]], requires_grad=True)
bias_ih_l0 Parameter containin

In [29]:
h0

tensor([[[ 0.5393, -0.9091,  0.9402, -1.4900,  0.1866, -0.3970],
         [ 0.0562,  1.8954, -1.5275, -0.6741,  0.0876, -0.4109],
         [ 0.2122,  0.9042,  1.3288,  0.0218, -0.6126, -1.2201]]])

In [30]:
output

tensor([[[-0.0703, -0.1515, -0.4850, -0.8797, -0.8236,  0.4887],
         [-0.8354,  0.9541,  0.7582,  0.0332,  0.3140,  0.0116],
         [ 0.2374,  0.6054, -0.2692, -0.7329,  0.0626, -0.3358]],

        [[-0.3125, -0.5395,  0.2788, -0.3241,  0.5325,  0.3993],
         [ 0.8191, -0.0661,  0.6571, -0.8298,  0.6776,  0.3198],
         [ 0.1874,  0.4300,  0.1034, -0.7347, -0.3388,  0.4242]],

        [[ 0.3521,  0.1150, -0.2523, -0.8367, -0.2562,  0.8334],
         [ 0.0030,  0.5310, -0.6974, -0.8220, -0.6874,  0.6507],
         [-0.1303,  0.3852, -0.3412, -0.3859, -0.4627,  0.2651]],

        [[-0.6936,  0.4551, -0.3243,  0.2684, -0.6356, -0.2093],
         [ 0.2645, -0.5352,  0.3698, -0.4584,  0.5627,  0.4910],
         [-0.4694,  0.1697,  0.4721, -0.0384,  0.2498,  0.0185]],

        [[ 0.1964,  0.4399,  0.0150, -0.3440,  0.2403,  0.1750],
         [-0.8032,  0.7423, -0.2932, -0.2237, -0.7556,  0.3850],
         [ 0.4888,  0.0246,  0.3506, -0.6491, -0.0554,  0.1433]]],
       grad_fn=

In [31]:
hn

tensor([[[ 0.1964,  0.4399,  0.0150, -0.3440,  0.2403,  0.1750],
         [-0.8032,  0.7423, -0.2932, -0.2237, -0.7556,  0.3850],
         [ 0.4888,  0.0246,  0.3506, -0.6491, -0.0554,  0.1433]]],
       grad_fn=<StackBackward0>)

In [42]:
rnn = nn.RNN(4, 2)
x = torch.randn(5, 3, 4)
ho = torch.zeros(1, 3, 2)

In [45]:
output, hn = rnn(x, ho)

In [46]:
output

tensor([[[-0.9245,  0.9471],
         [ 0.1771, -0.6176],
         [-0.6732, -0.6043]],

        [[-0.3165, -0.0583],
         [-0.5062, -0.5569],
         [-0.3195, -0.3139]],

        [[-0.0111,  0.3180],
         [ 0.4852, -0.3483],
         [-0.3556, -0.6856]],

        [[-0.9428,  0.6842],
         [ 0.5917, -0.4573],
         [-0.4848,  0.3325]],

        [[ 0.6976, -0.3138],
         [ 0.4942,  0.4296],
         [-0.5441, -0.4838]]], grad_fn=<StackBackward0>)

In [47]:
hn

tensor([[[ 0.6976, -0.3138],
         [ 0.4942,  0.4296],
         [-0.5441, -0.4838]]], grad_fn=<StackBackward0>)